name: Java CI/CD Pipeline Simulasi

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build and Test with Maven
      run: mvn -B package --file pom.xml

    - name: Simulate Continuous Deployment
      run: |
        echo "Build & Test sukses!"
        echo "Mensimulasikan proses deployment ke server production..."
        echo "Deployment berhasil diselesaikan."